// ============================================================
// 向后兼容 — 转发到 core/types
// ============================================================

export type {
  MessageRole,
  ContentBlockType,
  ContentBlock,
  Message,
  AgentConfig,
  AgentStatus,
  AgentState,
  TokenUsage,
  AgentEventType,
  AgentEventMap,
  JSONSchema,
  ToolSchema,
  Tool,
  ToolResult,
  ToolCall,
  IToolRegistry,
  StreamEventType,
  StopReason,
  StreamEvent,
  ProviderConfig,
  ILLMProvider,
  RetryConfig,
  AppConfig,
  UITheme,
  UIConfig,
  PermissionLevel,
  PermissionConfig,
  ToolsConfig,
  IConfigLoader,
} from '../core/types';
